### ISSUE TITLE
Which day's NCLT data is used?

### ISSUE THREAD

**Issue by wpumain** [BIT-MJY/SeqOT#4]
In your readme file, you said that the data of October 8, 2012 is used, but the data of February 5, 2012 is used in the project code. 
https://github.com/BIT-MJY/SeqOT/blob/dffd2b5f74893a5b5c300ec98865785ba57ef367/config/config.yml#L5
Then I just started to configure the program, which day should I download the data? ? Currently I have downloaded the relevant data according to the link on the readme.

**Comment by BIT-MJY** [comment]
Sorry for that. October 8, 2012 is a mistake. We use 2012-01-08 rather than 2012-10-08.

For place recognition, you should use one trajectory to generate database, and use the other one to generate query scans. In this repo, the database is from 2012-01-08, and the query scans are from 2012-02-05. You can find more details in our [paper](https://ieeexplore.ieee.org/document/9994714).

**Comment by wpumain** [comment]
Think you for your help.
